# Generated by Django 5.2.1 on 2025-05-23 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movilidad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camaraseguridad',
            name='zona_critica',
        ),
        migrations.RemoveField(
            model_name='seguimientovehiculo',
            name='camara',
        ),
        migrations.RemoveField(
            model_name='seguimientovehiculo',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='semaforo',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='semaforo',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='semaforo',
            name='tiempo_ciclo',
        ),
        migrations.RemoveField(
            model_name='semaforo',
            name='zona_critica',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='camara',
        ),
        migrations.AddField(
            model_name='seguimientovehiculo',
            name='camara_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seguimientovehiculo',
            name='vehiculo_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semaforo',
            name='estado',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='camara_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accidente',
            name='camara',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movilidad.camaraseguridad'),
        ),
        migrations.AlterField(
            model_name='camaraseguridad',
            name='latitud',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='camaraseguridad',
            name='longitud',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='seguimientovehiculo',
            name='velocidad_detectada',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='traficotiemporeal',
            name='latitud',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='traficotiemporeal',
            name='longitud',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='traficotiemporeal',
            name='nivel_congestion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='zonacritica',
            name='latitud',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='zonacritica',
            name='longitud',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='zonacritica',
            name='tipo_problema',
            field=models.CharField(max_length=100),
        ),
    ]
